kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-data
  labels:
    type: local
    app: sonar
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/data/postgresql/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-postgres
  labels:
    app: sonar
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
