kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonar-data-pc
  labels:
    type: local
    app: sonar
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - jenkins
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/sonarqube/data/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-data-pvc
  labels:
    app: sonar
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
