apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3-pvc
  namespace: nexus3
  labels:
    app: nexus3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi