apiVersion: v1
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nexus3-local
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/nexus3-local