apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-dep
  namespace: akuznetsova
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: registry-ci.playpit.by/helloworld-akuznetsova:_buildNumber_
        imagePullPolicy: Always

        ports:
        - name: tom-port
          containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  namespace: akuznetsova
spec:
  selector:
    app: tomcat
  ports:
  - name: tom-svc-port
    port: 8080
    targetPort: tom-port
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: akuznetsova
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /helloworld-ws/$1
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - akuznetsova-app.k8s.playpit.by
    secretName: letsencrypt-prod
  rules:
  - host: akuznetsova-app.k8s.playpit.by
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: tomcat-svc
          servicePort: tom-svc-port
