---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv-data
  namespace: jenkins
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jenkins
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarqube-data-storage
  local:
    path: /opt/sonarqube/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc-data
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sonarqube-data-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  namespace: jenkins
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:lts
        env:
        - name: SONARQUBE_JDBC_USERNAME
          value: sonar
        - name: SONARQUBE_JDBC_PASSWORD
          value: sonar
        - name: SONARQUBE_JDBC_URL
          value: "jdbc:postgresql://postgresql-service:5432/sonar"
        ports:
        - name: sonarqube-port
          containerPort: 9000
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-pvc-data
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: jenkins
  labels:
    app: sonarqube
spec:
  selector:
    app: sonarqube
  type: ClusterIP
  ports:
  - name: sonarqube-svc
    protocol: TCP
    port: 9000
    targetPort: sonarqube-port
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarqube-ingress
  namespace: jenkins
spec:
  rules:
  - host: sonar
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarqube-service
          servicePort: sonarqube-svc
