FROM tomcat:8-jre8

MAINTAINER "Hleb Kanonik <hleb_kanonik@epam.com">

ADD /var/jenkins_home/workspace/helloworld-project/helloworld-project/helloworld-ws/target/helloworld-ws.war /usr/local/tomcat/webapps/
