apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-db
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql/
    