apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-vol-pv-data
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jenkins
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/nexus

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-vol-pvc-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3
        resources:
          requests:
            memory: 1024Mi
          limits:
            memory: 2048Mi

        ports:
        - name: nexus-port
          containerPort: 8081
        - name: nexus-port1
          containerPort: 18081
        - name: nexus-port2
          containerPort: 28082

        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-vol-pvc-data

---

apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
spec:
  selector:
    app: nexus
  type: LoadBalancer
  ports:
  - name: nexussvcport
    port: 80
    targetPort: nexus-port
  - name: nexussvcport1
    port: 18081
    targetPort: nexus-port1
  - name: nexussvcport2
    port: 28082
    targetPort: nexus-port2

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nexus.k8s.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nexus-service
          servicePort: nexussvcport


