apiVersion: v1
kind: PersistentVolume
metadata:
  name: localvolume-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/vagrant/jenkins_home
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: localvolume-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pod-volumes-localvolume-volume
          mountPath: /var/jenkins_home
        - name: dockersock
          mountPath: "/var/run/docker.sock"
        - name: docker
          mountPath: "/usr/bin/docker"
      volumes:
      - name: pod-volumes-localvolume-volume
        persistentVolumeClaim:
          claimName: localvolume-pvc
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: docker
        hostPath:
          path: /usr/bin/docker
