apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: jenkins
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jenkins
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgresql-storage
  local:
    path: /opt/postgresql
