apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv-data
  namespace: jenkins
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jenkins
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonarqube-data-storage
  local:
    path: /opt/sonarqube/data
