apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc-data
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sonarqube-data-storage
  resources:
    requests:
      storage: 1Gi
