apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-d
  labels:
    app: jenkins-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 993    # Group ID of docker group on k8s nodes.
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - name: jenkinsport
          containerPort: 8080
        - name: jenkinsport2
          containerPort: 50000
        volumeMounts:
        - name: jenkins-volume
          mountPath: /var/jenkins_home # JENKINS_HOME
        - name: kubectl
          mountPath: "/usr/bin/kubectl"
        - name: dockersock
          mountPath: "/var/run/docker.sock"
        - name: docker
          mountPath: "/usr/bin/docker"

      volumes:
      - name: jenkins-volume
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: kubectl
        hostPath:
          path: /usr/bin/kubectl
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: docker
        hostPath:
          path: /usr/bin/docker


