apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-vol-pv
  namespace: postgres
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
  capacity: 
    storage: 2Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /tmp/postgres
---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vol-pvc
  namespace: postgres
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-dep
  namespace: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER
          value: sonar          
        - name: POSTGRES_PASSWORD
          value: admin
        ports:
        - name: post-port1
          containerPort: 8080
        volumeMounts:
        - name: postgres-dep-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-dep-volume
        persistentVolumeClaim:
          claimName: postgres-vol-pvc
---


apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: post-svc-port1
    port: 8080
    targetPort: post-port1












